name: Deploy Website (FTP)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to Hostinger FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: "157.173.216.88"
          username: "u551651590"
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: "./dist/client/"
          server-dir: "/public_html/"
          dangerous-clean-slate: false
