name: Deploy Website (FTP)

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Create .htaccess
        run: |
          cat > dist/.htaccess << 'EOF'
          Options -MultiViews
          RewriteEngine On
          RewriteBase /

          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule ^ index.html [L]

          EOF

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: "157.173.216.88"
          username: "u551651590"
          password: "Singer@1984"
          port: 21
          local-dir: "dist/"
          server-dir: "/public_html/"
          dangerous-clean-slate: false
